# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abc5a9628d603bd7edd7455b6389db74391210e6a45527b874d08b3375c65ef1702977c4a26b9bca6b7ea691e8009ab26dfe62457002e3c221fe579a94ee3deb

test:
  secret_key_base: 1c9348734fbb504a3b3668baaacc7f7dee8c635bd5c85b233627a9610660e1fcb4efbc1e7ea77cbc600cda6455edae2f47efbaec014514cad0a739133cc89e4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
